integration:
  name: minitest
includes:
  - test
requires:
  - ./config/environment
environment_variables:
  RAILS_ENV: test
matcher:
  subjects:
    - Booking::DaySchedule
    - Booking::Appointment
