name: CI
on: [push, pull_request]
jobs:
  test:
    env:
      RAILS_ENV: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    - run: bin/rails db:setup
    - run: bin/rails t
  mutate:
    env:
      RAILS_ENV: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    - run: bin/rails db:setup
    - run: bin/mutant run
